name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Build the Docker image
        if: success() && github.ref != 'refs/head/master'
        run: docker build . --file Dockerfile --tag demo-naturalis-api:0.0.1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: success() && github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        if: success() && github.ref == 'refs/heads/master'
        uses: docker/setup-buildx-action@v1
      - name: Docker push
        if: success() && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-naturalis-api:latest
